version: '3.3'
services:
  haproxy:
    container_name: web_haproxy
    image: haproxytech/haproxy-alpine:latest
    ports:
      - "80:80"
    volumes:
      - ./.docker/config/web_haproxy/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      backend:
        ipv4_address: 172.20.0.15

  web_one:
    container_name: web_one
    image: nginx:stable-alpine
    ports:
      - "8121:80"
    volumes:
      - ./.docker/config/web_one/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/config/web_one/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/config/web_one/nginx/html/index.html:/usr/share/nginx/html/index.html
    networks:
      backend:
        ipv4_address: 172.20.0.11

  web_two:
    container_name: web_two
    image: nginx:stable-alpine
    ports:
      - "8122:80"
    volumes:
      - ./.docker/config/web_two/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/config/web_two/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/config/web_two/nginx/html/index.html:/usr/share/nginx/html/index.html
    networks:
      backend:
        ipv4_address: 172.20.0.12

  web_three:
    container_name: web_three
    image: nginx:stable-alpine
    ports:
      - "8123:80"
    volumes:
      - ./.docker/config/web_three/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/config/web_three/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/config/web_three/nginx/html/index.html:/usr/share/nginx/html/index.html
    networks:
      backend:
        ipv4_address: 172.20.0.13

  web_mirror:
    container_name: web_mirror
    image: nginx:stable-alpine
    ports:
      - "8120:80"
    networks:
      backend:
        ipv4_address: 172.20.0.14

networks:
  backend:
    ipam:
      config:
        - subnet: 172.20.0.0/24
